// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package timesheet.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the Timesheet module

	public static java.lang.String getBillingService()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Timesheet.BillingService");
	}

	public static java.lang.String getBillingServicePassword()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Timesheet.BillingServicePassword");
	}

	public static java.lang.String getDefaultPassword()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Timesheet.DefaultPassword");
	}
}