// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package timesheet.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Timesheet module

	public static java.lang.String getDefaultPassword()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Timesheet.DefaultPassword");
	}
}