// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { NativeModules } from "react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} notificationId - This field is required.
 * @returns {Promise.<void>}
 */
export async function CancelScheduledNotification(notificationId) {
	// BEGIN USER CODE
    if (NativeModules && !NativeModules.RNFirebase) {
        return Promise.reject(new Error("Firebase module is not available in your app"));
    }
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const firebase = require("react-native-firebase");
    if (!notificationId) {
        return Promise.reject(new Error("Input parameter 'Notification id' is required"));
    }
    firebase.notifications().cancelNotification(notificationId);
    return Promise.resolve();
	// END USER CODE
}
