// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.
function CreateCalendarEvent(title, startDate, endDate, location, allDay, notes) {
    // BEGIN USER CODE
    // Documentation https://github.com/vonovak/react-native-add-calendar-event#creating-an-event
    const AddCalendarEvent = require("react-native-add-calendar-event");
    return AddCalendarEvent.presentEventCreatingDialog({
        title,
        startDate: startDate && startDate.toISOString(),
        endDate: endDate && endDate.toISOString(),
        location,
        allDay,
        notes
    }).then(result => {
        if (result.action === "SAVED") {
            return result.eventIdentifier;
        }
        return;
    });
    // END USER CODE
}
