// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.
function EditCalendarEvent(eventId) {
    // BEGIN USER CODE
    // Documentation https://github.com/vonovak/react-native-add-calendar-event#editing-an-event
    const AddCalendarEvent = require("react-native-add-calendar-event");
    if (!eventId) {
        throw new TypeError("Input parameter 'Event id' is required");
    }
    return AddCalendarEvent.presentEventEditingDialog({
        eventId
    }).then(() => true);
    // END USER CODE
}
