// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { NativeModules } from "react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Big} badgeNumber - This field is required. Should be greater than or equal to 0.
 * @returns {Promise.<void>}
 */
export async function SetBadgeNumber(badgeNumber) {
	// BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/notifications/reference/Notifications#setBadge
    if (NativeModules && !NativeModules.RNFirebase) {
        return Promise.reject(new Error("Firebase module is not available in your app"));
    }
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const firebase = require("react-native-firebase");
    if (!badgeNumber) {
        return Promise.reject(new Error("Input parameter 'Badge number' is required"));
    }
    if (badgeNumber.lt(0)) {
        return Promise.reject(new Error("Input parameter 'Badge number' should be zero or greater"));
    }
    return firebase.notifications().setBadge(Number(badgeNumber));
	// END USER CODE
}
