// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package timesheet.proxies;

public class Submission
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject submissionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Timesheet.Submission";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Task("Task"),
		Date("Date"),
		Hours("Hours"),
		Minutes("Minutes"),
		Client("Client"),
		Tag("Tag"),
		Status("Status"),
		_Type("_Type"),
		Notes("Notes"),
		TimeID("TimeID"),
		RequestedBy("Timesheet.RequestedBy"),
		ReviewedBy("Timesheet.ReviewedBy");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Submission(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Timesheet.Submission"));
	}

	protected Submission(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject submissionMendixObject)
	{
		if (submissionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Timesheet.Submission", submissionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Timesheet.Submission");

		this.submissionMendixObject = submissionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Submission.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static timesheet.proxies.Submission initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return timesheet.proxies.Submission.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static timesheet.proxies.Submission initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new timesheet.proxies.Submission(context, mendixObject);
	}

	public static timesheet.proxies.Submission load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return timesheet.proxies.Submission.initialize(context, mendixObject);
	}

	public static java.util.List<timesheet.proxies.Submission> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<timesheet.proxies.Submission> result = new java.util.ArrayList<timesheet.proxies.Submission>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Timesheet.Submission" + xpathConstraint))
			result.add(timesheet.proxies.Submission.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Task
	 */
	public final java.lang.String getTask()
	{
		return getTask(getContext());
	}

	/**
	 * @param context
	 * @return value of Task
	 */
	public final java.lang.String getTask(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Task.toString());
	}

	/**
	 * Set value of Task
	 * @param task
	 */
	public final void setTask(java.lang.String task)
	{
		setTask(getContext(), task);
	}

	/**
	 * Set value of Task
	 * @param context
	 * @param task
	 */
	public final void setTask(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String task)
	{
		getMendixObject().setValue(context, MemberNames.Task.toString(), task);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of Hours
	 */
	public final java.lang.Integer getHours()
	{
		return getHours(getContext());
	}

	/**
	 * @param context
	 * @return value of Hours
	 */
	public final java.lang.Integer getHours(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Hours.toString());
	}

	/**
	 * Set value of Hours
	 * @param hours
	 */
	public final void setHours(java.lang.Integer hours)
	{
		setHours(getContext(), hours);
	}

	/**
	 * Set value of Hours
	 * @param context
	 * @param hours
	 */
	public final void setHours(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer hours)
	{
		getMendixObject().setValue(context, MemberNames.Hours.toString(), hours);
	}

	/**
	 * @return value of Minutes
	 */
	public final java.lang.Integer getMinutes()
	{
		return getMinutes(getContext());
	}

	/**
	 * @param context
	 * @return value of Minutes
	 */
	public final java.lang.Integer getMinutes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Minutes.toString());
	}

	/**
	 * Set value of Minutes
	 * @param minutes
	 */
	public final void setMinutes(java.lang.Integer minutes)
	{
		setMinutes(getContext(), minutes);
	}

	/**
	 * Set value of Minutes
	 * @param context
	 * @param minutes
	 */
	public final void setMinutes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minutes)
	{
		getMendixObject().setValue(context, MemberNames.Minutes.toString(), minutes);
	}

	/**
	 * @return value of Client
	 */
	public final java.lang.String getClient()
	{
		return getClient(getContext());
	}

	/**
	 * @param context
	 * @return value of Client
	 */
	public final java.lang.String getClient(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Client.toString());
	}

	/**
	 * Set value of Client
	 * @param client
	 */
	public final void setClient(java.lang.String client)
	{
		setClient(getContext(), client);
	}

	/**
	 * Set value of Client
	 * @param context
	 * @param client
	 */
	public final void setClient(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String client)
	{
		getMendixObject().setValue(context, MemberNames.Client.toString(), client);
	}

	/**
	 * @return value of Tag
	 */
	public final java.lang.String getTag()
	{
		return getTag(getContext());
	}

	/**
	 * @param context
	 * @return value of Tag
	 */
	public final java.lang.String getTag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tag.toString());
	}

	/**
	 * Set value of Tag
	 * @param tag
	 */
	public final void setTag(java.lang.String tag)
	{
		setTag(getContext(), tag);
	}

	/**
	 * Set value of Tag
	 * @param context
	 * @param tag
	 */
	public final void setTag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tag)
	{
		getMendixObject().setValue(context, MemberNames.Tag.toString(), tag);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final timesheet.proxies.Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final timesheet.proxies.Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return timesheet.proxies.Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(timesheet.proxies.Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, timesheet.proxies.Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final timesheet.proxies._Type get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final timesheet.proxies._Type get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames._Type.toString());
		if (obj == null)
			return null;

		return timesheet.proxies._Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(timesheet.proxies._Type _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, timesheet.proxies._Type _type)
	{
		if (_type != null)
			getMendixObject().setValue(context, MemberNames._Type.toString(), _type.toString());
		else
			getMendixObject().setValue(context, MemberNames._Type.toString(), null);
	}

	/**
	 * @return value of Notes
	 */
	public final java.lang.String getNotes()
	{
		return getNotes(getContext());
	}

	/**
	 * @param context
	 * @return value of Notes
	 */
	public final java.lang.String getNotes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Notes.toString());
	}

	/**
	 * Set value of Notes
	 * @param notes
	 */
	public final void setNotes(java.lang.String notes)
	{
		setNotes(getContext(), notes);
	}

	/**
	 * Set value of Notes
	 * @param context
	 * @param notes
	 */
	public final void setNotes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notes)
	{
		getMendixObject().setValue(context, MemberNames.Notes.toString(), notes);
	}

	/**
	 * @return value of TimeID
	 */
	public final java.lang.Long getTimeID()
	{
		return getTimeID(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeID
	 */
	public final java.lang.Long getTimeID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TimeID.toString());
	}

	/**
	 * Set value of TimeID
	 * @param timeid
	 */
	public final void setTimeID(java.lang.Long timeid)
	{
		setTimeID(getContext(), timeid);
	}

	/**
	 * Set value of TimeID
	 * @param context
	 * @param timeid
	 */
	public final void setTimeID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long timeid)
	{
		getMendixObject().setValue(context, MemberNames.TimeID.toString(), timeid);
	}

	/**
	 * @return value of RequestedBy
	 */
	public final timesheet.proxies.MendixSSOUser getRequestedBy() throws com.mendix.core.CoreException
	{
		return getRequestedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestedBy
	 */
	public final timesheet.proxies.MendixSSOUser getRequestedBy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		timesheet.proxies.MendixSSOUser result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestedBy.toString());
		if (identifier != null)
			result = timesheet.proxies.MendixSSOUser.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestedBy
	 * @param requestedby
	 */
	public final void setRequestedBy(timesheet.proxies.MendixSSOUser requestedby)
	{
		setRequestedBy(getContext(), requestedby);
	}

	/**
	 * Set value of RequestedBy
	 * @param context
	 * @param requestedby
	 */
	public final void setRequestedBy(com.mendix.systemwideinterfaces.core.IContext context, timesheet.proxies.MendixSSOUser requestedby)
	{
		if (requestedby == null)
			getMendixObject().setValue(context, MemberNames.RequestedBy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestedBy.toString(), requestedby.getMendixObject().getId());
	}

	/**
	 * @return value of ReviewedBy
	 */
	public final timesheet.proxies.MendixSSOUser getReviewedBy() throws com.mendix.core.CoreException
	{
		return getReviewedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of ReviewedBy
	 */
	public final timesheet.proxies.MendixSSOUser getReviewedBy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		timesheet.proxies.MendixSSOUser result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReviewedBy.toString());
		if (identifier != null)
			result = timesheet.proxies.MendixSSOUser.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReviewedBy
	 * @param reviewedby
	 */
	public final void setReviewedBy(timesheet.proxies.MendixSSOUser reviewedby)
	{
		setReviewedBy(getContext(), reviewedby);
	}

	/**
	 * Set value of ReviewedBy
	 * @param context
	 * @param reviewedby
	 */
	public final void setReviewedBy(com.mendix.systemwideinterfaces.core.IContext context, timesheet.proxies.MendixSSOUser reviewedby)
	{
		if (reviewedby == null)
			getMendixObject().setValue(context, MemberNames.ReviewedBy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReviewedBy.toString(), reviewedby.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return submissionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final timesheet.proxies.Submission that = (timesheet.proxies.Submission) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Timesheet.Submission";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
